# Generated by Django 4.0.5 on 2022-12-06 14:13

from django.db import migrations

import colorama
from colorama import Fore, Back

from .helper.unit1 import unit1
from .helper.unit2 import unit2

colorama.init(autoreset=True)


class Migration(migrations.Migration):

    def insert_to_unit(apps, schema_editor):

        print("\n STARTING")

        Unit1 = apps.get_model('core', 'Unit1')
        Unit2 = apps.get_model('core', 'Unit2')

        for unit_item1 in unit1:

            # аймаг хот
            unit1_code = unit_item1['code_list_code']
            unit1_name = unit_item1['code_list_name']

            created_unit1 = Unit1.objects.create(
                name=unit1_name,
                code=unit1_code
            )

            unit2_data = unit2[unit1_code]
            for unit2_item in unit2_data:

                # сум дүүрэг
                unit2_code = unit2_item['code_list_code']
                unit2_name = unit2_item['code_list_name']

                created_unit2 = Unit2.objects.create(
                    name=unit2_name,
                    code=unit2_code,
                    unit1=created_unit1
                )

            print(Fore.LIGHTMAGENTA_EX + unit1_code + " code той " + unit1_name + " орж дуусав ")

        print(Back.GREEN + Fore.BLACK + "___DONE___")

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_to_unit),
    ]
