# Generated by Django 4.0.5 on 2022-12-06 14:17

from django.db import migrations
from main.utils.consts import init_work_calendar_kinds


class Migration(migrations.Migration):

    def insert_data(apps, schema):
        WorkCalendarKind = apps.get_model("core", 'WorkCalendarKind')
        Orgs = apps.get_model("core", 'Orgs')
        SubOrgs = apps.get_model("core", 'SubOrgs')
        Salbars = apps.get_model("core", 'Salbars')

        for kind in init_work_calendar_kinds:
            for org in Orgs.objects.all():
                WorkCalendarKind \
                    .objects \
                    .create(
                        org=org,
                        title=kind['title'],
                        textColor=kind['textColor'],
                    )

        for kind in init_work_calendar_kinds:
            for suborg in SubOrgs.objects.all():
                WorkCalendarKind \
                    .objects \
                    .create(
                        org=suborg.org,
                        sub_org=suborg,
                        title=kind['title'],
                        textColor=kind['textColor'],
                    )

        for kind in init_work_calendar_kinds:
            for salbar in Salbars.objects.all():
                WorkCalendarKind \
                    .objects \
                    .create(
                        org=salbar.org,
                        sub_org=salbar.sub_orgs,
                        salbar=salbar,
                        title=kind['title'],
                        textColor=kind['textColor'],
                    )

    dependencies = [
        ('core', '0004_auto_20221206_1416'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
