# Generated by Django 4.0.5 on 2022-12-06 14:20

from django.db import migrations
from main.utils.consts import init_static_shagnal
from main.utils.consts import init_shagnal


class Migration(migrations.Migration):

    def insert_static_shagnal(apps, schema):
        StaticShagnal = apps.get_model("core", 'StaticShagnal')

        for kind in init_static_shagnal:
            StaticShagnal \
                .objects \
                .create(
                    name=kind['name'],
                    order=kind['order'],
                )

    def insert_shagnal(apps, schema):
        Shagnal = apps.get_model("core", 'Shagnal')
        Orgs = apps.get_model("core", 'Orgs')

        for kind in init_shagnal:
            for org in Orgs.objects.all():
                Shagnal \
                    .objects \
                    .create(
                        org=org,
                        name=kind['name'],
                        order=kind['order'],
                    )

    dependencies = [
        ('core', '0008_auto_20221206_1418'),
    ]

    operations = [
        migrations.RunPython(insert_static_shagnal),
        migrations.RunPython(insert_shagnal),
    ]
