# Generated by Django 4.0.5 on 2022-12-06 14:21

from django.db import migrations
from main.utils.consts import init_notif_types


class Migration(migrations.Migration):

    def _insert_notif(apps, schema):
        NotificationType = apps.get_model("core", 'NotificationType')

        for ntype in init_notif_types:
            NotificationType.objects.create(
                name=ntype['name'],
                color=ntype['color'],
                level=ntype['level']
            )

    dependencies = [
        ('core', '0010_auto_20221206_1421'),
    ]

    operations = [
        migrations.RunPython(_insert_notif)
    ]
