# Generated by Django 4.0.5 on 2022-12-06 14:22

from django.db import migrations, transaction
from main.utils.consts import init_skills


class Migration(migrations.Migration):

    def _insert_datas(apps, shcema):
        StaticGroupSkills = apps.get_model("core", "StaticGroupSkills")
        StaticSkills = apps.get_model("core", "StaticSkills")
        StaticSkillsDefinations = apps.get_model("core", "StaticSkillsDefinations")

        with transaction.atomic():
            for gskill in init_skills:
                gkill_obj = StaticGroupSkills.objects.create(name=gskill['name'])
                for skill in gskill['skills']:
                    skill_obj = StaticSkills.objects.create(name=skill['name'], group=gkill_obj)
                    for sdef in skill['defs']:
                        StaticSkillsDefinations.objects.create(name=sdef['name'], skill=skill_obj)

    dependencies = [
        ('core', '0011_auto_20221206_1421'),
    ]

    operations = [
        migrations.RunPython(_insert_datas)
    ]
