# Generated by Django 4.0.5 on 2022-12-06 14:23

from django.db import migrations

import colorama
from colorama import Fore, Back

from .helper.permissions import permissions

colorama.init(autoreset=True)


class Migration(migrations.Migration):

    def insert_to_permissions(apps, schema_editor):

        print("\n STARTING")

        Permissions = apps.get_model('core', 'Permissions')

        for permissions_item in permissions:

            check_perm = Permissions.objects.filter(name=permissions_item['name'])
            if check_perm is None:
                # аймаг хот
                permissions_name = permissions_item['name']
                permissions_description = permissions_item['description']

                created_permissions = Permissions.objects.create(
                    name=permissions_name,
                    description=permissions_description
                )

        print(Back.GREEN + Fore.BLACK + "___DONE___")

    dependencies = [
        ('core', '0013_auto_20221206_1422'),
    ]

    operations = [
        migrations.RunPython(insert_to_permissions),
    ]
