# Generated by Django 4.0.5 on 2022-12-06 14:23

from django.db import migrations
import colorama
from colorama import Fore, Back

colorama.init(autoreset=True)


class Migration(migrations.Migration):

    def insert_to_working_time_schedule_type(apps, schema_editor):

        print("\n WorkingTimeScheduleType моделийн утгууд хадгалах процесс эхлэж байна.")

        working_time_schedule_types = [
            {
                'name' : '7 хоногийн өдрүүдээр',
                'code' : '1'
            },
            {
                'name' : 'Ажлын X цаг, амралтын Y цаг',
                'code' : '2'
            },
            {
                'name' : 'Үл хамаарах цагийн хуваарийн төрөл',
                'code' : '3'
            },
        ]

        WorkingTimeScheduleType = apps.get_model('core', 'WorkingTimeScheduleType')

        for working_time_schedule_type_item in working_time_schedule_types:
            check_type = WorkingTimeScheduleType.objects.filter(code=working_time_schedule_type_item['code'])
            # Байхгүй бол шинээр үүсгэнэ
            if not check_type:
                type_name = working_time_schedule_type_item['name']
                type_code = working_time_schedule_type_item['code']

                WorkingTimeScheduleType.objects.create(
                    name=type_name,
                    code=type_code
                )

        print(Back.GREEN + Fore.BLACK + "WorkingTimeScheduleType үүсж дууслаа!")

    dependencies = [
        ('core', '0014_auto_20221206_1423'),
    ]

    operations = [
        migrations.RunPython(insert_to_working_time_schedule_type),
    ]
