# Generated by Django 4.0.5 on 2022-12-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    def _fix_shagnal_data(apps, schema):
        """ shagnal ийн kind нь static байвал employee -с user ийг хайж хадгалах """

        ShagnalEmployee = apps.get_model('core', 'ShagnalEmployee')
        qs = ShagnalEmployee.objects.filter(kind=1)

        for shagnal_employee in qs:
            if not shagnal_employee.user:
                shagnal_employee.user = shagnal_employee.employee.user
                shagnal_employee.save()

    dependencies = [
        ('core', '0016_auto_20221206_1424'),
    ]

    operations = [
        migrations.RunPython(_fix_shagnal_data)
    ]
