# Generated by Django 4.0.5 on 2022-12-06 14:25

from django.db import migrations

import colorama
from colorama import Fore, Back

from main.utils.user_percent import CalcUserPercent

colorama.init(autoreset=True)


class Migration(migrations.Migration):

    def _set_user_progress(apps, schema_editor):
        print("\n STARTING")

        User = apps.get_model('core', 'User')
        users = User.objects.all()
        for user in users:
            CalcUserPercent(user_id=user.id).calc()

        print(Back.GREEN + Fore.BLACK + "___DONE___")

    dependencies = [
        ('core', '0018_auto_20221206_1425'),
    ]

    operations = [
        migrations.RunPython(_set_user_progress)
    ]
