# Generated by Django 4.0.5 on 2022-12-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    def _insert_data(apps, schema):
        Config = apps.get_model("core", 'Config')

        init_config = [
            {
                "name": "NOTIF_MAX",
                "value": "10"
            }
        ]

        for config in init_config:
            Config.objects.create(**config)

    dependencies = [
        ('core', '0019_auto_20221206_1425'),
    ]

    operations = [
        migrations.RunPython(_insert_data)
    ]
