# Generated by Django 4.0.5 on 2022-12-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    def _fix_data(apps, shcema):
        UserInfo = apps.get_model('core', 'UserInfo')
        User = apps.get_model('core', 'User')
        user = User.objects.filter(email='admin@yopmail.com').first()
        if not user.userinfo_set.exists():
            UserInfo.objects.create(
                user=user,
                last_name='admin',
                first_name='admin',
                action_status=2, # UserInfo.APPROVED,
                action_status_type=3, # UserInfo.ACTION_TYPE_ALL,
            )

    dependencies = [
        ('core', '0020_auto_20221206_1426'),
    ]

    operations = [
        migrations.RunPython(_fix_data)
    ]
