# Generated by Django 4.0.5 on 2022-12-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    def _create(apps, schema):
        CountNumber = apps.get_model('core', 'CountNumber')
        CountNumber.objects.create(
            name='time_register_employee',
            count=1
        )

    dependencies = [
        ('core', '0022_auto_20221206_1427'),
    ]

    operations = [
        migrations.RunPython(_create)
    ]
