# Generated by Django 4.0.5 on 2022-12-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20221206_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgposition',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Багш эсэх'),
        ),
    ]
