# Generated by Django 4.0.5 on 2022-12-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_orgposition_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='register_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ажилтны код'),
        ),
    ]
