# Generated by Django 4.0.5 on 2023-08-10 15:49

import colorama
from colorama import Fore, Back

from django.db import migrations

colorama.init(autoreset=True)


class Migration(migrations.Migration):

    def insert_main_position(apps, schema_editor):

        print("\n MainPosition моделийн утгууд хадгалах процесс эхлэж байна.")

        main_position_types = [
            {
                'name' : 'Захирал',
                'code': '2'
            },
            {
                'name' : 'Дэд захирал',
                'code': '3'
            },
            {
                'name' : 'Салбар сургуулийн захирал',
                'code': '4'
            },
            {
                'name' : 'Салбар сургуулийн дэд захирал',
                'code': '5'
            },
            {
                'name' : 'Бүрэлдэхүүн сургуулийн захирал',
                'code': '6'
            },
            {
                'name' : 'Бүрэлдэхүүн сургуулийн дэд захирал',
                'code': '7'
            },
            {
                'name' : 'Захиргаа, хэлтэс нэгжийн газрын дарга',
                'code': '8'
            },
            {
                'name' : 'Сургалтын бодлого зохицуулалтын газрын дарга',
                'code': '9'
            },
            {
                'name' : 'Захиргаа, хэлтэс нэгжийн албаны дарга',
                'code': '10'
            },
            {
                'name' : 'Сургалтын албаны дарга',
                'code': '11'
            },
            {
                'name' : 'Салбар, тэнхмийн эрхлэгч',
                'code': '12'
            },
            {
                'name' : 'Хуулийн зөвлөх',
                'code': '13'
            },
            {
                'name' : 'Хяналт, шинжилгээ үнэлгээний мэргэжилтэн',
                'code': '14'
            },
            {
                'name' : 'Захиргаа, хүний нөөцийн мэргэжилтэн',
                'code': '15'
            },
            {
                'name' : 'Сургалтын албаны мэргэжилтэн',
                'code': '16'
            },
            {
                'name' : 'Мэдээлэл, технологийн мэргэжилтэн',
                'code': '17'
            },
            {
                'name' : 'Эрдэм шинжилгээ, судалгааны мэргэжилтэн',
                'code': '18'
            },
            {
                'name' : 'Оюутны хөгжил, үйлчилгээний газрын ажилтан',
                'code': '19'
            },
            {
                'name' : 'Хүрээлэн, төвийн судлаач',
                'code': '20'
            },
            {
                'name' : 'Үндсэн багш',
                'code': '21'
            },
            {
                'name' : 'Цагийн багш',
                'code': '22'
            },
            {
                'name' : 'Тэнхмийн туслах ажилтан',
                'code': '23'
            },
            {
                'name' : 'Эрдэм шинжилгээ, судалгааны туслах ажилтан',
                'code': '24'
            },
            {
                'name' : 'Нийгмийн ажилтан',
                'code': '25'
            },
            {
                'name' : 'Захирлын туслах, нарийн бичиг',
                'code': '26'
            },
            {
                'name' : 'Эмч',
                'code': '27'
            },
            {
                'name' : 'Номын санч',
                'code': '28'
            },
            {
                'name' : 'Оюутны байрны менежер, эрхлэгч',
                'code': '29'
            },
            {
                'name' : 'Инженер, техникч',
                'code': '30'
            },
            {
                'name' : 'Лаборант',
                'code': '31'
            },
            {
                'name' : 'Эдийн засагч, нягтлан бодогч',
                'code': '32'
            },
            {
                'name' : 'Хангамж, худалдан авалтын ажилтан, нярав',
                'code': '33'
            },
            {
                'name' : 'Бичиг хэргийн эрхлэгч, ажилтан',
                'code': '34'
            },
            {
                'name' : 'Жижүүр, манаач, сахиул',
                'code': '35'
            },
            {
                'name' : 'Үйлчлэгч',
                'code': '36'
            },
            {
                'name' : 'Бусад ажилтан',
                'code': '37'
            },
            {
                'name' : 'Хөгжлийн бэрхшээлтэй ажиллагчид',
                'code': '38'
            },
            {
                'name' : 'Үндсэн багш',
                'code': '39'
            },
        ]

        MainPosition = apps.get_model('core', 'MainPosition')

        MainPosition.objects.all().delete()

        for main_position_item in main_position_types:
            MainPosition.objects.create(name=main_position_item['name'], code=main_position_item['code'])

        print(Back.GREEN + Fore.BLACK + "MainPosition үүсж дууслаа!")

    dependencies = [
        ('core', '0024_auto_20230810_1428'),
    ]

    operations = [
        migrations.RunPython(insert_main_position),
    ]
