# Generated by Django 4.0.5 on 2022-12-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_employee_register_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='register_code',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Ажилтны код'),
        ),
    ]
