# Generated by Django 4.0.5 on 2023-01-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_salbars_is_hotolboriin_bag_suborgs_is_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='experience_mnun_year',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='МҮИС-д ажилласан жил'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='experience_year',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Нийт ажилласан жил'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_disabled',
            field=models.BooleanField(default=False, null=True, verbose_name='Хөгжлийн бэрхшээлтэй эсэх'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_pension',
            field=models.BooleanField(default=False, null=True, verbose_name='Тэтгэвэрт гарсан эсэх'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_training_licence',
            field=models.BooleanField(default=False, null=True, verbose_name='Багшлах эрхийн сургалтанд суусан эсэх'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='suutsnii_torol',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'ерөнхий мэдээлэл'), (2, 'нэмэлт мэдээлэл'), (3, 'бүх мэдээлэл')], db_index=True, default=None, null=True, verbose_name='Сууцны төрөл'),
        ),
    ]
