# Generated by Django 4.0.5 on 2023-03-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_userinfo_suutsnii_torol'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgs',
            name='email',
            field=models.EmailField(error_messages={'unique': 'И-мэйл давхцсан байна'}, max_length=254, null=True, unique=True, verbose_name='И-мэйл'),
        ),
        migrations.AddField(
            model_name='orgs',
            name='home_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Факс'),
        ),
        migrations.AddField(
            model_name='orgs',
            name='name_eng',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orgs',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Утасны дугаар'),
        ),
        migrations.AddField(
            model_name='orgs',
            name='todorkhoilolt_signature',
            field=models.ImageField(blank=True, null=True, upload_to='orgs/logo', verbose_name='лого'),
        ),
        migrations.AddField(
            model_name='orgs',
            name='todorkhoilolt_tamga',
            field=models.ImageField(blank=True, null=True, upload_to='orgs/logo', verbose_name='лого'),
        ),
    ]
