# Generated by Django 4.0.5 on 2023-03-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_orgs_email_orgs_home_phone_orgs_name_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgs',
            name='todorkhoilolt_approved',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orgs',
            name='todorkhoilolt_rank',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
