# Generated by Django 4.0.5 on 2023-03-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_orgs_todorkhoilolt_approved_orgs_todorkhoilolt_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfamilymember',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Утасны дугаар'),
        ),
        migrations.AddField(
            model_name='userfamilymember',
            name='register',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Регистерийн дугаар'),
        ),
    ]
