# Generated by Django 4.0.5 on 2023-03-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_userfamilymember_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_type',
            field=models.PositiveIntegerField(choices=[(1, 'Үндсэн'), (2, 'Энгийн хүн'), (3, 'Оюутан')], db_index=True, default=1, verbose_name='Хэрэглэгчийн төлөв'),
        ),
    ]
