# Generated by Django 4.0.5 on 2023-04-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_user_login_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Оюутны код')),
            ],
            options={
                'db_table': 'lms_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Нэвтрэх нэр')),
                ('password', models.CharField(max_length=256, verbose_name='Нууц үг')),
            ],
            options={
                'db_table': 'lms_studentlogin',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='basic_salary_information',
            field=models.IntegerField(blank=True, null=True, verbose_name='Үндсэн цалингийн мэдээлэл'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_wage_information',
            field=models.IntegerField(blank=True, null=True, verbose_name='Хөлсөөр ажиллах цалингийн мэдээлэл'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hourly_wage_information',
            field=models.IntegerField(blank=True, null=True, verbose_name='Нэг цагийн цалингийн мэдээлэл'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_for_hire',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Хөлсөөр ажиллах эсэх'),
        ),
    ]
