# Generated by Django 4.0.5 on 2023-04-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_student_studentlogin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='basic_salary_information',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Үндсэн цалингийн мэдээлэл'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_wage_information',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Хөлсөөр ажиллах цалингийн мэдээлэл'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_wage_information',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Нэг цагийн цалингийн мэдээлэл'),
        ),
        migrations.CreateModel(
            name='HolidayDayInYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Огноо')),
                ('every_year', models.BooleanField(default=False, verbose_name='Жил болгон давхцдаг эсэх')),
                ('year', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Аль он')),
                ('name', models.CharField(max_length=256, verbose_name='Амралтын өдрийн нэр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.orgs', verbose_name='Байгууллага')),
            ],
        ),
    ]
