# Generated by Django 4.0.5 on 2023-05-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_employee_basic_salary_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgs',
            name='register',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Байгууллагын регистр:'),
        ),
        migrations.AlterField(
            model_name='timescheduleregister',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Ажилласан'), (2, 'Тасалсан'), (3, 'Ажлын өдөр шалтгаантай'), (4, 'Амралт'), (5, 'Шалтгаантай мөртлөө амралтын өдөр'), (6, 'Шалтгаантай өдөр ажлын амралтын гэдэг нь мэдэгдээгүй'), (7, 'Ажлын өдөр тусгай амралт таарсан өдөр')], verbose_name='Цаг бүртгэлийн төрөл'),
        ),
    ]
