# Generated by Django 4.0.5 on 2023-05-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_orgs_register_alter_timescheduleregister_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgs',
            name='email_host',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EMAIL HOST'),
        ),
        migrations.AddField(
            model_name='orgs',
            name='email_host_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HOST NAME'),
        ),
        migrations.AddField(
            model_name='orgs',
            name='email_host_user',
            field=models.EmailField(max_length=255, null=True, verbose_name='Системийн и-мэйл'),
        ),
        migrations.AddField(
            model_name='orgs',
            name='email_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EMAIL PASSWORD'),
        ),
        migrations.AddField(
            model_name='orgs',
            name='email_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='EMAIL PORT'),
        ),
        migrations.AddField(
            model_name='orgs',
            name='email_use_tls',
            field=models.BooleanField(default=False, verbose_name='USE TLS'),
        ),
    ]
