# Generated by Django 4.0.5 on 2023-05-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_orgs_email_host_orgs_email_host_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgs',
            name='sign_zahiral',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Гарын үсэг зурах захиралын нэр'),
        ),
    ]
