# Generated by Django 4.0.5 on 2023-05-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_salbars_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborgs',
            name='name_eng',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Байгууллага нэр англи'),
        ),
        migrations.AddField(
            model_name='suborgs',
            name='name_uig',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Байгууллага нэр уйгаржин'),
        ),
        migrations.AddField(
            model_name='suborgs',
            name='tsol_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Цол нэр'),
        ),
        migrations.AddField(
            model_name='suborgs',
            name='tsol_name_eng',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Цол нэр англи'),
        ),
        migrations.AddField(
            model_name='suborgs',
            name='tsol_name_uig',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Цол нэр уйгаржин'),
        ),
        migrations.AddField(
            model_name='suborgs',
            name='zahiral_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Захирал нэр'),
        ),
        migrations.AddField(
            model_name='suborgs',
            name='zahiral_name_eng',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Захирал нэр англи'),
        ),
        migrations.AddField(
            model_name='suborgs',
            name='zahiral_name_uig',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Захирал нэр уйгаржин'),
        ),
    ]
