# Generated by Django 4.0.5 on 2023-05-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_suborgs_name_eng_suborgs_name_uig_suborgs_tsol_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='time_register_employee',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Хэрэглэгчийн цагаа бүртгүүлэх ID'),
        ),
    ]
