# Generated by Django 4.0.5 on 2023-05-29 14:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_notification_tree_org_notification_tree_org_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='notification',
            name='kurs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='notification',
            name='oyutans',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='notification',
            name='profs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='notification',
            name='scope_kind',
            field=models.IntegerField(choices=[(1, 'Байгууллага'), (2, 'Дэд байгууллага'), (3, 'Салбар'), (4, 'Албан тушаал'), (5, 'Алба хаагч'), (6, 'Хэрэглэгч'), (7, 'Бүгд'), (8, 'Оюутан'), (9, 'Мэргэжил'), (10, 'Курс'), (11, 'Анги')]),
        ),
    ]
