# Generated by Django 4.0.5 on 2023-06-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_notification_groups_notification_kurs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tree_kind',
            field=models.BooleanField(default=False),
        ),
    ]
