# Generated by Django 4.0.5 on 2023-05-31 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_notification_tree_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttimevacationregister',
            name='agreed',
        ),
        migrations.RemoveField(
            model_name='requesttimevacationregister',
            name='reason_for_rejection',
        ),
        migrations.RemoveField(
            model_name='requesttimevacationregister',
            name='resolved_date',
        ),
        migrations.RemoveField(
            model_name='requesttimevacationregister',
            name='special_reason',
        ),
        migrations.AddField(
            model_name='orgvacationtypesbranchtypes',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Зэрэглэл'),
        ),
        migrations.AddField(
            model_name='orgvacationtypesbranchtypes',
            name='org_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.orgposition', verbose_name='Гарын үсэг зурах албан тушаал'),
        ),
        migrations.AlterField(
            model_name='orgvacationtypes',
            name='many_days_vacation',
            field=models.BooleanField(default=True, null=True, verbose_name='Олон өдрийн чөлөө'),
        ),
        migrations.AlterField(
            model_name='orgvacationtypes',
            name='one_day_vacation',
            field=models.BooleanField(default=True, null=True, verbose_name='Нэг өдрийн чөлөө'),
        ),
        migrations.AlterField(
            model_name='orgvacationtypesbranchtypes',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хүсэлтийн хуудасан дээрх өмнө нь юу гэж бичигдэхийг заана'),
        ),
        migrations.CreateModel(
            name='Correspond_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Хариулсан огноо')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='Зөвшөөрсөн эсэх')),
                ('message', models.CharField(max_length=500, null=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.orgposition', verbose_name='Хариулсан албан тушаалтан')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.requesttimevacationregister', verbose_name='Чөлөөний хүсэлт')),
            ],
        ),
    ]
