# Generated by Django 4.0.5 on 2023-06-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_requesttimevacationregister_agreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspond_answer',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Хэн баталсан'),
            preserve_default=False,
        ),
    ]
