# Generated by Django 4.0.5 on 2023-06-07 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_correspond_answer_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Төгссөн он сар')),
                ('days', models.IntegerField(blank=True, null=True, verbose_name='Хэд хоног амрах өдөр')),
                ('state', models.PositiveIntegerField(choices=[(1, 'Хүсэлт илгээгдсэн'), (2, 'Татгалзсан'), (3, 'Зөвшөөрсөн')], db_index=True, default=1, verbose_name='Хүсэлтийн төpөл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Ажилтан')),
            ],
        ),
    ]
