# Generated by Django 4.0.5 on 2023-06-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_vacationemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationemployee',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'Хүсэлт илгээгдсэн'), (2, 'Татгалзсан'), (3, 'Зөвшөөрсөн'), (4, 'Цуцалсан')], db_index=True, default=1, verbose_name='Хүсэлтийн төpөл'),
        ),
    ]
