# Generated by Django 4.0.5 on 2023-06-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_vacationemployee_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestions',
            name='is_rate_teacher',
            field=models.BooleanField(default=False, verbose_name='Багшийн үнэлэх асуулт эсэх'),
        ),
    ]
