# Generated by Django 4.0.5 on 2023-08-15 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_userprofessioninfo_where_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrOrderFormEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachements/%Y/%m/%d')),
                ('state', models.PositiveIntegerField(choices=[(1, 'Хүсэлт илгээгдсэн'), (2, 'Татгалзсан'), (3, 'Зөвшөөрсөн'), (4, 'Цуцалсан')], db_index=True, default=1, verbose_name='Хүсэлтийн төpөл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Ажилтан')),
            ],
        ),
    ]
