# Generated by Django 4.0.5 on 2023-08-17 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_hrorderformemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrorderformemployee',
            name='file',
            field=models.FileField(upload_to='hr-order-form/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='ViolationRegistrationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='violation_registration_page/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Ажилтан')),
            ],
        ),
    ]
